### ISSUE TITLE
Conflict with rails-settings-cached gem

### ISSUE THREAD

**Issue by LosYear** [justinfrench/formtastic#1130]
I'm trying to use 'rails-settings-cached' gem to store some settings in database. Simple model of this plugin has following fields: 'id', 'var', 'VALUE', 'thing_id', 'thing_type', 'created_at', 'updated_at'. I decided to add simple UI at the backend of my appication where user can add/update entries. 
My form looks simple:
```ruby
<%= semantic_form_for [:admin, @setting], :html => {:class => "form-horizontal"} do |f| %>
    <%= f.semantic_errors :var, :value%>
    <%= f.inputs do %>
        <%= f.input :var %>
        <%= f.input :value %>
    <% end %>
    <%= f.actions :class => 'form-group' do %>
        <div class="col-lg-offset-2 col-lg-8">
          <%= f.action :submit %>
          <%= f.action :cancel %>
        </div>
    <% end %>
<% end %>
``` 
But when I try to run my application at webpage with this form I get an error: `no implicit conversion of nil into String`. I think that the reason is `value` keyword. Look at Full trace:
```
/usr/local/rvm/rubies/ruby-2.0.0-p0/lib/ruby/2.0.0/psych.rb:205:in `parse'
/usr/local/rvm/rubies/ruby-2.0.0-p0/lib/ruby/2.0.0/psych.rb:205:in `parse_stream'
/usr/local/rvm/rubies/ruby-2.0.0-p0/lib/ruby/2.0.0/psych.rb:153:in `parse'
/usr/local/rvm/rubies/ruby-2.0.0-p0/lib/ruby/2.0.0/psych.rb:129:in `load'
rails-settings-cached (0.4.1) lib/rails-settings/settings.rb:105:in `value'
formtastic (2.3.1) lib/formtastic/helpers/file_column_detection.rb:9:in `is_file?'
formtastic (2.3.1) lib/formtastic/helpers/input_helper.rb:260:in `default_input_type'
formtastic (2.3.1) lib/formtastic/helpers/input_helper.rb:237:in `input'
app/views/admin/settings/_form.html.erb:5:in `block (2 levels) in _app_views_admin_settings__form_html_erb___996650244_88302790'
actionpack (4.0.2) lib/action_view/helpers/capture_helper.rb:38:in `block in capture'
actionpack (4.0.2) lib/action_view/helpers/capture_helper.rb:200:in `with_output_buffer'
actionpack (4.0.2) lib/action_view/helpers/capture_helper.rb:38:in `capture'
formtastic-bootstrap (3.0.0) lib/formtastic-bootstrap/helpers/fieldset_wrapper.rb:17:in `field_set_and_list_wrapping'
formtastic-bootstrap (3.0.0) lib/formtastic-bootstrap/helpers/inputs_helper.rb:18:in `inputs'
app/views/admin/settings/_form.html.erb:3:in `block in _app_views_admin_settings__form_html_erb___996650244_88302790'
actionpack (4.0.2) lib/action_view/helpers/capture_helper.rb:38:in `block in capture'
actionpack (4.0.2) lib/action_view/helpers/capture_helper.rb:200:in `with_output_buffer'
actionpack (4.0.2) lib/action_view/helpers/capture_helper.rb:38:in `capture'
actionpack (4.0.2) lib/action_view/helpers/form_helper.rb:435:in `form_for'
formtastic (2.3.1) lib/formtastic/helpers/form_helper.rb:174:in `block in semantic_form_for'
formtastic (2.3.1) lib/formtastic/helpers/form_helper.rb:197:in `with_custom_field_error_proc'
formtastic (2.3.1) lib/formtastic/helpers/form_helper.rb:173:in `semantic_form_for'
```
How can this problem be solved?

**Comment by justinfrench** [comment]
I don't know sorry. If you can provide a simple Rails app that replicates the issue, I'll be glad to run it and see if I can find the issue and come up with a solution, but with so many different gems in that trace, it's really hard to know where to look first.

**Comment by LosYear** [comment]
I created simple Rails application. You can see it here https://github.com/LosYear/formtastic-conflict
Just go to "/" or "settings/new" to see error

**Comment by justinfrench** [comment]
Hello, thanks so much for making the sample project so quickly, it really helped me make the most of my time on this — most people don't! I spent a good hour with this on two separate occasions, and I don't know what's wrong sorry.

If you follow the framework instead of the application trace, you can see that the exceptions are happening outside of Formtastic:

```
/Users/me/.rbenv/versions/2.0.0-p576/lib/ruby/2.0.0/psych.rb:205:in `parse'
/Users/me/.rbenv/versions/2.0.0-p576/lib/ruby/2.0.0/psych.rb:205:in `parse_stream'
/Users/me/.rbenv/versions/2.0.0-p576/lib/ruby/2.0.0/psych.rb:153:in `parse'
/Users/me/.rbenv/versions/2.0.0-p576/lib/ruby/2.0.0/psych.rb:129:in `load'
rails-settings-cached (0.4.1) lib/rails-settings/settings.rb:105:in `value'
formtastic (2.3.1) lib/formtastic/helpers/file_column_detection.rb:9:in `is_file?'
formtastic (2.3.1) lib/formtastic/helpers/input_helper.rb:260:in `default_input_type'
formtastic (2.3.1) lib/formtastic/helpers/input_helper.rb:237:in `input'
actionpack (4.0.2) lib/action_view/helpers/capture_helper.rb:38:in `block in capture'
actionpack (4.0.2) lib/action_view/helpers/capture_helper.rb:200:in `with_output_buffer'
actionpack (4.0.2) lib/action_view/helpers/capture_helper.rb:38:in `capture'
formtastic (2.3.1) lib/formtastic/helpers/fieldset_wrapper.rb:32:in `field_set_and_list_wrapping'
formtastic (2.3.1) lib/formtastic/helpers/inputs_helper.rb:297:in `inputs'
actionpack (4.0.2) lib/action_view/helpers/capture_helper.rb:38:in `block in capture'
actionpack (4.0.2) lib/action_view/helpers/capture_helper.rb:200:in `with_output_buffer'
actionpack (4.0.2) lib/action_view/helpers/capture_helper.rb:38:in `capture'
actionpack (4.0.2) lib/action_view/helpers/form_helper.rb:435:in `form_for'
formtastic (2.3.1) lib/formtastic/helpers/form_helper.rb:174:in `block in semantic_form_for'
formtastic (2.3.1) lib/formtastic/helpers/form_helper.rb:197:in `with_custom_field_error_proc'
formtastic (2.3.1) lib/formtastic/helpers/form_helper.rb:173:in `semantic_form_for'
```

I'm not familiar with rails-settings at all, so I wasn't able to figure out if the issue was here in settings.rb (which isn't exactly a classic-looking ActiveRecord or ActiveModel class that Formtastic expects)…

```ruby
   #get the value field, YAML decoded
    def value
      YAML::load(self[:value])
    end
```

… or further up in the YAML loader, or back down the trace with what Formtastic was doing. If you don't need to do file uploading in your application, a workaround is to monkey-patch Formtastic:

```ruby
module Formtastic
  module Inputs
    module Base
      module Fileish
        def file?
          return false
        end
      end
    end
  end
end

module Formtastic
  module Helpers
    module FileColumnDetection
      def is_file?(method, options = {})
        return false
      end
    end
  end
end
```

If you need file upload and file column detection in your app, I'd recommend writing an `ActiveModel` class for `Setting` which behaves properly with Formtastic in isolation, then figure out how it should wrap or be backed by something like a `RailsSettings::CachedSettings`. This would let you experiment with different method names (if there's a clash in `value`, you could try `contents`) and isolate the issue. But that's a bit of work also.

I'd be curious to know if this sample app "works" with simple_form or even a regular Rails form (if they all fail, this is a strong sign it's not a Formtastic issue).

Good luck! I'm not sure what else I can do to help at this point, so I'm closing.
