### ISSUE TITLE
undefined method `safe_join' on rails 3.2.22.3

### ISSUE THREAD

**Issue by jess** [justinfrench/formtastic#1226]
Just upgraded to rails 3.2.22.3 (http://weblog.rubyonrails.org/2016/8/11/Rails-5-0-0-1-4-2-7-2-and-3-2-22-3-have-been-released/) and am getting this error `undefined method 'safe_join' for #<ActionView::Helpers::InstanceTag:0x007fa933677260>`. I tracked it back to formtastic. Guess the security fix in rails broke formtastic. Here's a sample app with just rails and formtastic: https://github.com/jess/form_test

To see the error:
```
bundle
rake db:create db:migrate
rails s
```

and visit /users/new

here's the trace:

```
actionpack (3.2.22.3) lib/action_view/helpers/tag_helper.rb:159:in `tag_option'
actionpack (3.2.22.3) lib/action_view/helpers/tag_helper.rb:150:in `block in tag_options'
actionpack (3.2.22.3) lib/action_view/helpers/tag_helper.rb:138:in `each_pair'
actionpack (3.2.22.3) lib/action_view/helpers/tag_helper.rb:138:in `tag_options'
actionpack (3.2.22.3) lib/action_view/helpers/tag_helper.rb:131:in `content_tag_string'
actionpack (3.2.22.3) lib/action_view/helpers/tag_helper.rb:97:in `content_tag'
actionpack (3.2.22.3) lib/action_view/helpers/active_model_helper.rb:20:in `content_tag'
actionpack (3.2.22.3) lib/action_view/helpers/form_tag_helper.rb:196:in `label_tag'
actionpack (3.2.22.3) lib/action_view/helpers/form_helper.rb:1029:in `to_label_tag'
actionpack (3.2.22.3) lib/action_view/helpers/form_helper.rb:668:in `label'
actionpack (3.2.22.3) lib/action_view/helpers/form_helper.rb:1320:in `label'
formtastic (3.1.4) lib/formtastic/inputs/base/labelling.rb:9:in `label_html'
formtastic (3.1.4) lib/formtastic/inputs/base/stringish.rb:9:in `block in to_html'
actionpack (3.2.22.3) lib/action_view/helpers/capture_helper.rb:40:in `block in capture'
actionpack (3.2.22.3) lib/action_view/helpers/capture_helper.rb:187:in `with_output_buffer'
actionpack (3.2.22.3) lib/action_view/helpers/capture_helper.rb:40:in `capture'
formtastic (3.1.4) lib/formtastic/inputs/base/wrapping.rb:11:in `input_wrapping'
formtastic (3.1.4) lib/formtastic/inputs/base/stringish.rb:8:in `to_html'
formtastic (3.1.4) lib/formtastic/helpers/input_helper.rb:242:in `input'
app/views/users/_form.html.erb:15:in `block (2 levels) in _app_views_users__form_html_erb___2014265595330243413_70182367044540'
actionpack (3.2.22.3) lib/action_view/helpers/capture_helper.rb:40:in `block in capture'
actionpack (3.2.22.3) lib/action_view/helpers/capture_helper.rb:187:in `with_output_buffer'
actionpack (3.2.22.3) lib/action_view/helpers/capture_helper.rb:40:in `capture'
formtastic (3.1.4) lib/formtastic/helpers/fieldset_wrapper.rb:32:in `field_set_and_list_wrapping'
formtastic (3.1.4) lib/formtastic/helpers/inputs_helper.rb:293:in `inputs'
app/views/users/_form.html.erb:14:in `block in _app_views_users__form_html_erb___2014265595330243413_70182367044540'
actionpack (3.2.22.3) lib/action_view/helpers/capture_helper.rb:40:in `block in capture'
actionpack (3.2.22.3) lib/action_view/helpers/capture_helper.rb:187:in `with_output_buffer'
actionpack (3.2.22.3) lib/action_view/helpers/capture_helper.rb:40:in `capture'
actionpack (3.2.22.3) lib/action_view/helpers/form_helper.rb:378:in `form_for'
formtastic (3.1.4) lib/formtastic/helpers/form_helper.rb:174:in `block in semantic_form_for'
formtastic (3.1.4) lib/formtastic/helpers/form_helper.rb:197:in `with_custom_field_error_proc'
formtastic (3.1.4) lib/formtastic/helpers/form_helper.rb:173:in `semantic_form_for'
app/views/users/_form.html.erb:1:in `_app_views_users__form_html_erb___2014265595330243413_70182367044540'
actionpack (3.2.22.3) lib/action_view/template.rb:145:in `block in render'
activesupport (3.2.22.3) lib/active_support/notifications.rb:125:in `instrument'
actionpack (3.2.22.3) lib/action_view/template.rb:143:in `render'
actionpack (3.2.22.3) lib/action_view/renderer/partial_renderer.rb:265:in `render_partial'
actionpack (3.2.22.3) lib/action_view/renderer/partial_renderer.rb:238:in `block in render'
actionpack (3.2.22.3) lib/action_view/renderer/abstract_renderer.rb:38:in `block in instrument'
activesupport (3.2.22.3) lib/active_support/notifications.rb:123:in `block in instrument'
activesupport (3.2.22.3) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
activesupport (3.2.22.3) lib/active_support/notifications.rb:123:in `instrument'
actionpack (3.2.22.3) lib/action_view/renderer/abstract_renderer.rb:38:in `instrument'
actionpack (3.2.22.3) lib/action_view/renderer/partial_renderer.rb:237:in `render'
actionpack (3.2.22.3) lib/action_view/renderer/renderer.rb:46:in `render_partial'
actionpack (3.2.22.3) lib/action_view/helpers/rendering_helper.rb:27:in `render'
app/views/users/new.html.erb:3:in `_app_views_users_new_html_erb__4108620437723581676_70182349405620'
actionpack (3.2.22.3) lib/action_view/template.rb:145:in `block in render'
activesupport (3.2.22.3) lib/active_support/notifications.rb:125:in `instrument'
actionpack (3.2.22.3) lib/action_view/template.rb:143:in `render'
actionpack (3.2.22.3) lib/action_view/renderer/template_renderer.rb:48:in `block (2 levels) in render_template'
actionpack (3.2.22.3) lib/action_view/renderer/abstract_renderer.rb:38:in `block in instrument'
activesupport (3.2.22.3) lib/active_support/notifications.rb:123:in `block in instrument'
activesupport (3.2.22.3) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
activesupport (3.2.22.3) lib/active_support/notifications.rb:123:in `instrument'
actionpack (3.2.22.3) lib/action_view/renderer/abstract_renderer.rb:38:in `instrument'
actionpack (3.2.22.3) lib/action_view/renderer/template_renderer.rb:47:in `block in render_template'
actionpack (3.2.22.3) lib/action_view/renderer/template_renderer.rb:55:in `render_with_layout'
actionpack (3.2.22.3) lib/action_view/renderer/template_renderer.rb:46:in `render_template'
actionpack (3.2.22.3) lib/action_view/renderer/template_renderer.rb:18:in `render'
actionpack (3.2.22.3) lib/action_view/renderer/renderer.rb:41:in `render_template'
actionpack (3.2.22.3) lib/action_view/renderer/renderer.rb:22:in `render'
actionpack (3.2.22.3) lib/abstract_controller/rendering.rb:110:in `_render_template'
actionpack (3.2.22.3) lib/action_controller/metal/streaming.rb:225:in `_render_template'
actionpack (3.2.22.3) lib/abstract_controller/rendering.rb:103:in `render_to_body'
actionpack (3.2.22.3) lib/action_controller/metal/renderers.rb:28:in `render_to_body'
actionpack (3.2.22.3) lib/action_controller/metal/compatibility.rb:50:in `render_to_body'
actionpack (3.2.22.3) lib/abstract_controller/rendering.rb:88:in `render'
actionpack (3.2.22.3) lib/action_controller/metal/rendering.rb:16:in `render'
actionpack (3.2.22.3) lib/action_controller/metal/instrumentation.rb:40:in `block (2 levels) in render'
activesupport (3.2.22.3) lib/active_support/core_ext/benchmark.rb:5:in `block in ms'
/Users/jess/.rubies/ruby-2.1.6/lib/ruby/2.1.0/benchmark.rb:294:in `realtime'
activesupport (3.2.22.3) lib/active_support/core_ext/benchmark.rb:5:in `ms'
actionpack (3.2.22.3) lib/action_controller/metal/instrumentation.rb:40:in `block in render'
actionpack (3.2.22.3) lib/action_controller/metal/instrumentation.rb:83:in `cleanup_view_runtime'
activerecord (3.2.22.3) lib/active_record/railties/controller_runtime.rb:24:in `cleanup_view_runtime'
actionpack (3.2.22.3) lib/action_controller/metal/instrumentation.rb:39:in `render'
actionpack (3.2.22.3) lib/action_controller/metal/implicit_render.rb:10:in `default_render'
actionpack (3.2.22.3) lib/action_controller/metal/mime_responds.rb:196:in `respond_to'
app/controllers/users_controller.rb:29:in `new'
actionpack (3.2.22.3) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
actionpack (3.2.22.3) lib/abstract_controller/base.rb:167:in `process_action'
actionpack (3.2.22.3) lib/action_controller/metal/rendering.rb:10:in `process_action'
actionpack (3.2.22.3) lib/abstract_controller/callbacks.rb:18:in `block in process_action'
activesupport (3.2.22.3) lib/active_support/callbacks.rb:414:in `_run__2945715754948220940__process_action__1816857563683703317__callbacks'
activesupport (3.2.22.3) lib/active_support/callbacks.rb:405:in `__run_callback'
activesupport (3.2.22.3) lib/active_support/callbacks.rb:385:in `_run_process_action_callbacks'
activesupport (3.2.22.3) lib/active_support/callbacks.rb:81:in `run_callbacks'
actionpack (3.2.22.3) lib/abstract_controller/callbacks.rb:17:in `process_action'
actionpack (3.2.22.3) lib/action_controller/metal/rescue.rb:29:in `process_action'
actionpack (3.2.22.3) lib/action_controller/metal/instrumentation.rb:30:in `block in process_action'
activesupport (3.2.22.3) lib/active_support/notifications.rb:123:in `block in instrument'
activesupport (3.2.22.3) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
activesupport (3.2.22.3) lib/active_support/notifications.rb:123:in `instrument'
actionpack (3.2.22.3) lib/action_controller/metal/instrumentation.rb:29:in `process_action'
actionpack (3.2.22.3) lib/action_controller/metal/params_wrapper.rb:207:in `process_action'
activerecord (3.2.22.3) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
actionpack (3.2.22.3) lib/abstract_controller/base.rb:121:in `process'
actionpack (3.2.22.3) lib/abstract_controller/rendering.rb:45:in `process'
actionpack (3.2.22.3) lib/action_controller/metal.rb:203:in `dispatch'
actionpack (3.2.22.3) lib/action_controller/metal/rack_delegation.rb:14:in `dispatch'
actionpack (3.2.22.3) lib/action_controller/metal.rb:246:in `block in action'
actionpack (3.2.22.3) lib/action_dispatch/routing/route_set.rb:73:in `call'
actionpack (3.2.22.3) lib/action_dispatch/routing/route_set.rb:73:in `dispatch'
actionpack (3.2.22.3) lib/action_dispatch/routing/route_set.rb:36:in `call'
journey (1.0.4) lib/journey/router.rb:68:in `block in call'
journey (1.0.4) lib/journey/router.rb:56:in `each'
journey (1.0.4) lib/journey/router.rb:56:in `call'
actionpack (3.2.22.3) lib/action_dispatch/routing/route_set.rb:608:in `call'
actionpack (3.2.22.3) lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'
rack (1.4.7) lib/rack/etag.rb:23:in `call'
rack (1.4.7) lib/rack/conditionalget.rb:25:in `call'
actionpack (3.2.22.3) lib/action_dispatch/middleware/head.rb:14:in `call'
actionpack (3.2.22.3) lib/action_dispatch/middleware/params_parser.rb:21:in `call'
actionpack (3.2.22.3) lib/action_dispatch/middleware/flash.rb:242:in `call'
rack (1.4.7) lib/rack/session/abstract/id.rb:210:in `context'
rack (1.4.7) lib/rack/session/abstract/id.rb:205:in `call'
actionpack (3.2.22.3) lib/action_dispatch/middleware/cookies.rb:341:in `call'
activerecord (3.2.22.3) lib/active_record/query_cache.rb:64:in `call'
activerecord (3.2.22.3) lib/active_record/connection_adapters/abstract/connection_pool.rb:479:in `call'
actionpack (3.2.22.3) lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
activesupport (3.2.22.3) lib/active_support/callbacks.rb:405:in `_run__242931011035810434__call__1656238274460534893__callbacks'
activesupport (3.2.22.3) lib/active_support/callbacks.rb:405:in `__run_callback'
activesupport (3.2.22.3) lib/active_support/callbacks.rb:385:in `_run_call_callbacks'
activesupport (3.2.22.3) lib/active_support/callbacks.rb:81:in `run_callbacks'
actionpack (3.2.22.3) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
actionpack (3.2.22.3) lib/action_dispatch/middleware/reloader.rb:65:in `call'
actionpack (3.2.22.3) lib/action_dispatch/middleware/remote_ip.rb:31:in `call'
actionpack (3.2.22.3) lib/action_dispatch/middleware/debug_exceptions.rb:16:in `call'
actionpack (3.2.22.3) lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'
railties (3.2.22.3) lib/rails/rack/logger.rb:32:in `call_app'
railties (3.2.22.3) lib/rails/rack/logger.rb:16:in `block in call'
activesupport (3.2.22.3) lib/active_support/tagged_logging.rb:22:in `tagged'
railties (3.2.22.3) lib/rails/rack/logger.rb:16:in `call'
actionpack (3.2.22.3) lib/action_dispatch/middleware/request_id.rb:22:in `call'
rack (1.4.7) lib/rack/methodoverride.rb:21:in `call'
rack (1.4.7) lib/rack/runtime.rb:17:in `call'
activesupport (3.2.22.3) lib/active_support/cache/strategy/local_cache.rb:72:in `call'
rack (1.4.7) lib/rack/lock.rb:15:in `call'
actionpack (3.2.22.3) lib/action_dispatch/middleware/static.rb:83:in `call'
railties (3.2.22.3) lib/rails/engine.rb:484:in `call'
railties (3.2.22.3) lib/rails/application.rb:231:in `call'
rack (1.4.7) lib/rack/content_length.rb:14:in `call'
railties (3.2.22.3) lib/rails/rack/log_tailer.rb:17:in `call'
rack (1.4.7) lib/rack/handler/webrick.rb:59:in `service'
/Users/jess/.rubies/ruby-2.1.6/lib/ruby/2.1.0/webrick/httpserver.rb:138:in `service'
/Users/jess/.rubies/ruby-2.1.6/lib/ruby/2.1.0/webrick/httpserver.rb:94:in `run'
/Users/jess/.rubies/ruby-2.1.6/lib/ruby/2.1.0/webrick/server.rb:295:in `block in start_thread'
```

**Comment by 11449** [comment]
Actually this is a bug in ActionView::Helpers::TagHelper itself, see: https://github.com/rails/rails/commit/4bcccf5ecd81a6272479537911b7d9760c5be164

They fix this one in version 3.2.22.4.

**Comment by jess** [comment]
nice, shall we close?

**Comment by 11449** [comment]
yep.

**Comment by cheeby** [comment]
excellent.  thanks for this.
