### ISSUE TITLE
NameError: uninitialized constant Formtastic::ActiveSupport

### ISSUE THREAD

**Issue by Victh** [justinfrench/formtastic#1253]
So I'm currently studying a rspec, formtastic & surveyor project.
Whenever I try to compile my project, using `bundle exec rspec`, I always get this error.
```
Failure/Error: require "surveyor"

NameError:
  uninitialized constant Formtastic::ActiveSupport
# ./.bundle/ruby/2.3.0/gems/formtastic-2.1.1/lib/formtastic.rb:5:in `<module:Formtastic>'
# ./.bundle/ruby/2.3.0/gems/formtastic-2.1.1/lib/formtastic.rb:4:in `<top (required)>'
# ./.bundle/ruby/2.3.0/gems/surveyor-1.4.0/lib/surveyor.rb:10:in `require'
# ./.bundle/ruby/2.3.0/gems/surveyor-1.4.0/lib/surveyor.rb:10:in `<top (required)>'
# ./lib/spec_helper.rb:4:in `require'
# ./lib/spec_helper.rb:4:in `<top (required)>'
```

My binaries and dependencies seems to be up-to-date (I already look up some issues here), but still didn't fixed it. Here's my `bundle show` result:

```
λ bundle show
Gems included by the bundle:
  * actionmailer (3.2.22.5)
  * actionpack (3.2.22.5)
  * activemodel (3.2.22.5)
  * activerecord (3.2.22.5)
  * activeresource (3.2.22.5)
  * activesupport (3.2.22.5)
  * arel (3.0.3)
  * builder (3.0.4)
  * bundler (1.15.4)
  * diff-lcs (1.3)
  * erubis (2.7.0)
  * fastercsv (1.5.5)
  * ffi (1.9.18)
  * formtastic (2.1.1)
  * haml (4.0.7)
  * hike (1.2.3)
  * i18n (0.8.6)
  * journey (1.0.4)
  * json (1.8.6)
  * mail (2.5.5)
  * mime-types (1.25.1)
  * multi_json (1.12.2)
  * mustache (0.99.4)
  * polyglot (0.3.5)
  * rabl (0.6.14)
  * rack (1.4.7)
  * rack-cache (1.7.1)
  * rack-ssl (1.3.4)
  * rack-test (0.6.3)
  * rails (3.2.22.5)
  * railties (3.2.22.5)
  * rake (12.1.0)
  * rb-fsevent (0.10.2)
  * rb-inotify (0.9.10)
  * rdoc (3.12.2)
  * rspec (3.6.0)
  * rspec-core (3.6.0)
  * rspec-expectations (3.6.0)
  * rspec-mocks (3.6.0)
  * rspec-support (3.6.0)
  * sass (3.5.1)
  * sass-listen (4.0.0)
  * sprockets (2.2.3)
  * surveyor (1.4.0)
  * thor (0.20.0)
  * tilt (1.4.1)
  * treetop (1.4.15)
  * tzinfo (0.3.53)
  * uuidtools (2.1.5)
```

The issue is going away if I remove the `require "surveyor"` line, though I obviously can't do that. I'm attaching the  project here.
[rspecsurveyor.zip](https://github.com/NUBIC/surveyor/files/1339249/rspecsurveyor.zip)

Thanks!

**Comment by mikz** [comment]
@Victh formtastic wasn't intended to be loaded without rails. You should load ActiveSupport yourself.

Also, that formtastic version (2.1.1) is really old and not supported.

**Comment by mikz** [comment]
Closing this due to inactivity. If you can reproduce this on latest version or can't fix it by manually requiring ActiveSupport please reopen this issue.
